"""Typed public API for the standalone atmogen physical-column engine."""

from .boundary import pressure_from_elevation
from .cloud_microphysics import (
    ParticleOpticalCoefficients,
    ParticlePopulation,
    PrecipitationStepResult,
    SedimentationResult,
    SettlingResult,
    cunningham_slip_correction,
    particle_optical_coefficients,
    precipitation_step,
    sedimentation_mass_flux,
    sphere_drag_coefficient,
    terminal_settling_velocity,
)
from .database import (
    BUILTIN_DATABASE,
    ChemicalDatabase,
    NRTLInteraction,
    ProvenanceClass,
    Reaction,
    Species,
    reaction_element_residual,
    species_moles_to_elements,
)
from .kinetics import (
    KineticsResult,
    arrhenius_rate_constant,
    expected_rate_coefficient_units,
    integrate_kinetics,
    reaction_rates,
)
from .liquids import (
    ActivityModel,
    IdealActivityModel,
    LiquidPhaseSplitResult,
    NRTLActivityModel,
    liquid_mixture_density_kg_m3,
    liquid_phase_stability,
    select_activity_model,
)
from .material_properties import (
    BUILTIN_FLUID_TRANSPORT,
    FluidTransportProperties,
    LiquidMixtureTransportFields,
    LiquidMixtureTransportProperties,
    fluid_transport_properties,
    liquid_mixture_transport_fields,
    liquid_mixture_transport_properties,
)
from .models import (
    ColumnBatchDiagnostics,
    ColumnBatchInput,
    ColumnBatchResult,
    ColumnInput,
    ColumnSurfaceBoundary,
    ElementInventory,
    Fidelity,
    LiquidPhaseState,
    PlanetChemistryResult,
    PlanetPhysicalState,
    SolverSettings,
    StellarSpectrum,
    SurfaceBoundaryMode,
    SurfaceReservoirs,
    VerticalProcessResult,
)
from .optics import (
    FresnelReflectance,
    MieEfficiencies,
    absorption_coefficient_m_inv,
    fresnel_reflectance,
    lorentz_lorenz_mix,
    mie_sphere_efficiencies,
    rayleigh_sphere_efficiencies,
)
from .photochemistry import (
    PhotolysisData,
    attenuate_actinic_photon_flux,
    column_photolysis_rates_s1,
    photolysis_rate_s1,
    spectral_irradiance_to_photon_flux,
)
from .radiation import blackbody_stellar_spectrum
from .solver import (
    column_state_fingerprint,
    solve_columns,
    solve_columns_with_diagnostics,
    solve_planet,
)
from .transport import (
    QuenchDiagnostic,
    VerticalTransportResult,
    eddy_diffusion_flux_mol_m2_s,
    integrate_eddy_diffusion,
    mixing_timescale_s,
    quench_diagnostic,
)
from .vertical_processes import layer_thickness_from_centres, solve_vertical_processes
from .version import API_SCHEMA_VERSION, DATA_SCHEMA_VERSION, __version__

__all__ = [
    "API_SCHEMA_VERSION",
    "ActivityModel",
    "BUILTIN_DATABASE",
    "BUILTIN_FLUID_TRANSPORT",
    "ChemicalDatabase",
    "ColumnBatchDiagnostics",
    "ColumnBatchInput",
    "ColumnBatchResult",
    "ColumnInput",
    "ColumnSurfaceBoundary",
    "DATA_SCHEMA_VERSION",
    "ElementInventory",
    "Fidelity",
    "FluidTransportProperties",
    "FresnelReflectance",
    "IdealActivityModel",
    "KineticsResult",
    "LiquidMixtureTransportFields",
    "LiquidMixtureTransportProperties",
    "LiquidPhaseSplitResult",
    "LiquidPhaseState",
    "MieEfficiencies",
    "NRTLActivityModel",
    "NRTLInteraction",
    "ParticleOpticalCoefficients",
    "ParticlePopulation",
    "PhotolysisData",
    "PlanetChemistryResult",
    "PlanetPhysicalState",
    "PrecipitationStepResult",
    "ProvenanceClass",
    "QuenchDiagnostic",
    "Reaction",
    "SedimentationResult",
    "SettlingResult",
    "SolverSettings",
    "Species",
    "StellarSpectrum",
    "SurfaceBoundaryMode",
    "SurfaceReservoirs",
    "VerticalProcessResult",
    "VerticalTransportResult",
    "__version__",
    "absorption_coefficient_m_inv",
    "arrhenius_rate_constant",
    "attenuate_actinic_photon_flux",
    "blackbody_stellar_spectrum",
    "column_photolysis_rates_s1",
    "column_state_fingerprint",
    "cunningham_slip_correction",
    "eddy_diffusion_flux_mol_m2_s",
    "expected_rate_coefficient_units",
    "fluid_transport_properties",
    "fresnel_reflectance",
    "integrate_eddy_diffusion",
    "integrate_kinetics",
    "layer_thickness_from_centres",
    "liquid_mixture_density_kg_m3",
    "liquid_mixture_transport_fields",
    "liquid_mixture_transport_properties",
    "liquid_phase_stability",
    "lorentz_lorenz_mix",
    "mie_sphere_efficiencies",
    "mixing_timescale_s",
    "particle_optical_coefficients",
    "photolysis_rate_s1",
    "precipitation_step",
    "pressure_from_elevation",
    "quench_diagnostic",
    "rayleigh_sphere_efficiencies",
    "reaction_element_residual",
    "reaction_rates",
    "sedimentation_mass_flux",
    "select_activity_model",
    "solve_columns",
    "solve_columns_with_diagnostics",
    "solve_planet",
    "solve_vertical_processes",
    "species_moles_to_elements",
    "spectral_irradiance_to_photon_flux",
    "sphere_drag_coefficient",
    "terminal_settling_velocity",
]
